-- AUTO-GENERATED by Claude DBT Test Generator
-- Model: stg_orders | Type: unit | Generated: 2024-01-15 09:32 UTC
-- DO NOT EDIT MANUALLY — regenerate via: python main.py --model stg_orders

{{ config(tags=['unit_test', 'auto_generated']) }}

-- ═══════════════════════════════════════════════════════════════════════════
-- TEST 1: discount_pct casting and is_discounted derivation
-- Verifies: TRY_TO_NUMBER cast, CASE branch for is_discounted flag
-- ═══════════════════════════════════════════════════════════════════════════
{% call dbt_unit_testing.test('stg_orders', 'discount flag and numeric cast') %}

  {% call dbt_unit_testing.mock_source('raw', 'orders') %}
    select * from (values
      -- happy path: discount > 0 → is_discounted TRUE
      ('O_GEN_01', 'C001', '2023-11-15', 'completed', 'standard',  'SAVE10',  '10',  current_timestamp),
      -- no discount → is_discounted FALSE
      ('O_GEN_02', 'C002', '2023-11-16', 'completed', 'express',   null,       '0',  current_timestamp),
      -- fractional discount
      ('O_GEN_03', 'C003', '2023-11-17', 'shipped',   'overnight', 'HALF50',  '50',  current_timestamp),
      -- promo code present but 0 discount (e.g. free shipping promo)
      ('O_GEN_04', 'C004', '2023-11-18', 'processing','standard',  'FREESHIP', '0',  current_timestamp)
    ) as t(order_id, customer_id, order_date, status, shipping_method, promo_code, discount_pct, _loaded_at)
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select * from (values
      ('O_GEN_01', 10.00, true,  'SAVE10'),
      ('O_GEN_02',  0.00, false, null),
      ('O_GEN_03', 50.00, true,  'HALF50'),
      ('O_GEN_04',  0.00, false, 'FREESHIP')  -- promo present, but no numeric discount → FALSE
    ) as t(order_id, discount_pct, is_discounted, promo_code)
  {% endcall %}

{% endcall %}


-- ═══════════════════════════════════════════════════════════════════════════
-- TEST 2: validated CTE filters — invalid rows must be excluded
-- Verifies: all four WHERE conditions in the validated CTE
-- ═══════════════════════════════════════════════════════════════════════════
{% call dbt_unit_testing.test('stg_orders', 'validated CTE filters invalid rows') %}

  {% call dbt_unit_testing.mock_source('raw', 'orders') %}
    select * from (values
      ('O_VALID',    'C001', '2023-11-15', 'completed',  'standard', null,  '0',   current_timestamp),  -- PASSES all checks
      ('O_NULL_ID',   null,  '2023-11-15', 'completed',  'standard', null,  '0',   current_timestamp),  -- FAIL: null customer_id
      ('O_BAD_STS',  'C002', '2023-11-15', 'PENDING',    'standard', null,  '0',   current_timestamp),  -- FAIL: bad status
      ('O_BAD_DATE', 'C003', 'NOT-A-DATE', 'completed',  'standard', null,  '0',   current_timestamp),  -- FAIL: bad date → TRY_TO_DATE returns null
      ('O_HIGH_DISC','C004', '2023-11-15', 'completed',  'standard', null, '150',  current_timestamp),  -- FAIL: discount > 100
      ('O_NEG_DISC', 'C005', '2023-11-15', 'completed',  'standard', null, '-5',   current_timestamp)   -- FAIL: discount < 0
    ) as t(order_id, customer_id, order_date, status, shipping_method, promo_code, discount_pct, _loaded_at)
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select * from (values
      ('O_VALID')   -- only 1 row should survive the validated CTE
    ) as t(order_id)
  {% endcall %}

{% endcall %}


-- ═══════════════════════════════════════════════════════════════════════════
-- TEST 3: NULL promo_code handling (NULLIF on empty string)
-- Verifies: NULLIF(TRIM(promo_code), '') correctly converts '' → NULL
-- ═══════════════════════════════════════════════════════════════════════════
{% call dbt_unit_testing.test('stg_orders', 'promo_code empty string becomes NULL') %}

  {% call dbt_unit_testing.mock_source('raw', 'orders') %}
    select * from (values
      ('O_NOPROMO',  'C001', '2023-11-15', 'completed', 'standard', '',      '0', current_timestamp),  -- empty → NULL
      ('O_SPACES',   'C002', '2023-11-15', 'completed', 'standard', '   ',   '0', current_timestamp),  -- spaces → NULL after TRIM
      ('O_HASPROMO', 'C003', '2023-11-15', 'completed', 'standard', 'CODE1', '5', current_timestamp)   -- real promo → kept
    ) as t(order_id, customer_id, order_date, status, shipping_method, promo_code, discount_pct, _loaded_at)
  {% endcall %}

  {% call dbt_unit_testing.expect() %}
    select * from (values
      ('O_NOPROMO',  null),
      ('O_SPACES',   null),
      ('O_HASPROMO', 'CODE1')
    ) as t(order_id, promo_code)
  {% endcall %}

{% endcall %}
